Fix CI pipeline error (#10)
Error 1: installation of ansible and ansible-lint was failing due to the following (see here)
```
Step 6/7 : RUN pip install ansible ansible-lint

 ---> Running in 24806e412e08

Collecting ansible

  Downloading https://files.pythonhosted.org/packages/ac/17/cb3ae6e4ae5b2d936ec5bf7e20cb91814e3af3ed27bbfcdf8a7253a016d5/ansible-4.8.0.tar.gz (36.1MB)

Collecting ansible-lint

  Downloading https://files.pythonhosted.org/packages/b0/44/9d47dd76a75de9e7b4acb13e1b8f75294d888852aadab51a9cef53b0e093/ansible-lint-5.2.1.tar.gz (356kB)

    Complete output from command python setup.py egg_info:

    Couldn't find index page for 'setuptools_scm' (maybe misspelled?)

    No local packages or download links found for setuptools-scm[toml]>=3.5.0

    Traceback (most recent call last):

      File "<string>", line 1, in <module>

      File "/tmp/pip-build-3ZR6Cv/ansible-lint/setup.py", line 12, in <module>

        setup_requires=["setuptools_scm[toml]>=3.5.0"],

      File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup

        _setup_distribution = dist = klass(attrs)

      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 265, in __init__

        self.fetch_build_eggs(attrs.pop('setup_requires'))

      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 289, in fetch_build_eggs

        parse_requirements(requires), installer=self.fetch_build_egg

      File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 618, in resolve

        dist = best[req.key] = env.best_match(req, self, installer)

      File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 862, in best_match

        return self.obtain(req, installer) # try and download/install

      File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 874, in obtain

        return installer(requirement)

      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 339, in fetch_build_egg

        return cmd.easy_install(req)

      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 617, in easy_install

        raise DistutilsError(msg)

    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('setuptools-scm[toml]>=3.5.0')

    

    ----------------------------------------

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-3ZR6Cv/ansible-lint/

You are using pip version 8.1.2, however version 21.3.1 is available.

You should consider upgrading via the 'pip install --upgrade pip' command.

The command '/bin/sh -c pip install ansible ansible-lint' returned a non-zero code: 1
```

Solution: pip needed to be upgraded, but pipv21 drops the support for python 2.7, so the command becomes pip install -U 'pip<21.0'

-----------------------------------------------------------------------------------

Error 2: ansible-lint run was failing with the following error (see here)

```
TEST: ansible-lint

/usr/lib/python2.7/site-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.

  from cryptography.exceptions import InvalidSignature

Couldn't parse task at /ansible-role-stress/tasks/main.yml:2 (conflicting action statements: find, __line__

The error appears to be in '<unicode string>': line 2, column 3, but may

be elsewhere in the file depending on the exact syntax problem.

(could not open file to display line))

AnsibleMapping([(u'name', u'Register screen session'), (u'find', AnsibleMapping([(u'paths', u'/var/run/screen/S-root/'), (u'file_type', u'any'), (u'patterns', u'*.stress'), ('__line__', 4), ('__file__', u'/ansible-role-stress/tasks/main.yml')])), (u'register', u'screen_files'), ('skipped_rules', [])])

ansible-lint syntax check was failed
```

Solution: ansible-lint is failing due to ansible-community/ansible-lint#892
This has been fixed in ansible-lint>4.3 but latest ansible-lint version available for python2 is 4.2.0
So the only alternative is to revert ansible to a previous version.
Since ansible-lint v4.3.0 is the first version to introduce the support for ansible>2.8 (see https://github.com/ansible-community/ansible-lint/releases/tag/v4.3.0 ), we force ansible to a version <2.8